version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTIC_PASSWORD=elastic
    ports:
      - "9200:9200"
    networks:
      - elk  # Adicionando a rede

  logstash:
    image: docker.elastic.co/logstash/logstash:8.5.3
    container_name: logstash
    ports:
      - "5044:5044"
      - "5000:5000"
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    environment:
      - "LS_JAVA_OPTS=-Xms512m -Xmx512m"
    depends_on:
      - elasticsearch  # Garantir que o ES suba antes do Logstash
    networks:
      - elk  # Adicionando a rede

  kibana:
    image: docker.elastic.co/kibana/kibana:8.4.0
    container_name: kibana
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - elk  # Adicionando a rede

networks:
  elk:  # Criando a rede
    driver: bridge
